version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"  # This is your PHP application
    depends_on:
      - db
    environment:
      - PHP_EXTENSION=gd,pdo_mysql
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # MariaDB

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "8080:80"  # Nginx web server
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
